name: KittenTTS Voice Sender

on:
  workflow_dispatch: # manual run
  repository_dispatch:
    types: [generate-voice]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache Poetry virtualenv + pip packages
      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root

      - name: Run TTS
        run: |
          poetry run python scripts/infer.py \
            --text "Hello from KittenTTS!" \
            --output tts_output.wav

      - name: Send to Telegram
        if: success()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ github.event.client_payload.chat_id || secrets.DEFAULT_CHAT_ID }}
        run: |
          curl -s -X POST \
            -H "Content-Type: multipart/form-data" \
            -F chat_id="$CHAT_ID" \
            -F voice="@tts_output.wav" \
            "https://api.telegram.org/bot8276916788:AAFqYhxqLjQMtw6BTmFzMf1AyYHWDhDVhtA/sendVoice"

      - name: Debug payload
        run: echo "Payload received: ${{ toJson(github.event.client_payload) }}"
